### ISSUE TITLE
FR: 7zip compression (along gzip?)

### ISSUE THREAD

**Issue by ephestione** [dolorosus/RaspiBackup#10]
adding the ability to deal with 7zip compression for those backups running during the night, were the long compression task isn't a problem, might be a nice idea, especially if combined with cloud uploading.
A few more lines of code could deal with installing p7zip-full (needed for the 7z command) if missing.

**Comment by dolorosus** [comment]
I would prefer a preflight check to enshure all needed software is installed instead of automated software install.
BUT for my application the compression is useless. 
My backup target is a btrfs-formatted file system and the target folder is located on a subvolume and has the compression option enabled.  
Before starting a new backup, a snapshot is taken and the oldest one removed.
To swap a snapshot, it is compressed and the compressed result is written directly to the target.

Advantage: the backup always takes place on the same file and only writes the delta for each backup. Nevertheless I have access to the last 14 backups via btrfs snapshots.

**Comment by ephestione** [comment]
Half of what you wrote flew over my head, but I still understood the underlying meaning.
Been reading about BTRFS several times during my backup planning web research, and I decided it's not useful for me to implement it at any level, for now. I still won't be able to compare with services like dropbox or mega in regard to safety and disaster recovery, so I'd like to cycle the occasional compressed 1gb backup online just for safe keeping :)

**Comment by dolorosus** [comment]
I understand your point. With your concept an integrated comprimation can make sense although I would prefer to do this in an another script.

BTW: a compressed version of my local backup (residing on the btrfs volume) is regulary uploaded to my google drive. This task is performed by another script ;-)

**Comment by ephestione** [comment]
would you mind creating a repo with that script in your profile, if that's allowed by your policy? I mean, why reinvent the wheel ;)
I have a working routine to upload and rotate on dropbox for my small rsyncs, but a whole system image, I want to send either to mega or drive, or both

**Comment by ephestione** [comment]
Wait, maybe there's no need, the gdrive application seems to be self explanatory, and I can create as many account as I need for each raspberry
