### ISSUE TITLE
Syntax error: Bad for loop variable

### ISSUE THREAD

**Issue by Vannixxo** [dolorosus/RaspiBackup#14]
Hello! I get this error when running the script

RaspiBackup.sh: 122: RaspiBackup.sh: Syntax error: Bad for loop variable

**Comment by dolorosus** [comment]
ok this looks strange, so I need some more information.

Please post the output of:

uname -a
bash --version
ls -lisa /bin/bash

**Comment by Vannixxo** [comment]
Here you have it:


pi@raspberrypi:~ $ uname -a
Linux raspberrypi 4.19.75-v7l+ #1270 SMP Tue Sep 24 18:51:41 BST 2019 armv7l GNU/Linux

pi@raspberrypi:~ $ bash --version
GNU bash, version 5.0.3(1)-release (arm-unknown-linux-gnueabihf)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

pi@raspberrypi:~ $ ls -lisa /bin/bash
494 904 -rwxr-xr-x 1 root root 925124 Apr 18  2019 /bin/bash

**Comment by dolorosus** [comment]
Stunning...

Software env looks good.

So the script seemed to be called by sh instead of bash. The shebang points to /bin/bash, but if you insist on running it with the shell (e.g. calling it with "sh RaspiBackup.sh") the shebang will not force the script to be run with bash.

Call it either with "bash RaspiBackup.sh" or simply "RaspiBackup.sh" and it will work.

**Comment by Vannixxo** [comment]
with bash, it goes! (without it, nope)
Thanks!

**Comment by dolorosus** [comment]
Surprise!
